import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import imageForm from '../public/bg-1.png'

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
      </Head>

      <main className={styles.main}>
      <section className="h-full gradient-form md:h-screen">
          <div className="lg:flex lg:flex-wrap g-0 flex xl:justify-center lg:justify-center justify-center items-center flex-wrap h-full">
            <div className="lg:w-6/12 flex items-center lg:rounded-r-lg lg:rounded-bl-none ">
              <Image
                    src={imageForm}
                    alt="Picture of the author"
                    className="w-full m-0"
                    height="950px"
                    width="720px"
                  />
            </div>
            <div className="lg:w-6/12 md:px-0 items-center my-8">
              <div className="md:p-12 md:mx-12 items-center ">
                <div className="text-left">
                  <h4 className="text-2xl font-bold mt-0 mb-8 pb-1 font-poppins">Daftar</h4>
                </div>
                <form>
                  <p className="mb-2 text-xs font-poppins">Nama</p>
                  <div className="mb-4 font-poppins">
                    <input
                      type="text"
                      className="form-control block w-full px-3 py-1.5 text-sm font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded-[16px] transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      id="exampleFormControlInput1"
                      placeholder="Username"
                    />
                  </div>
                  <p className="mb-2 text-xs font-poppins">Email</p>
                  <div className="mb-4 font-poppins">
                    <input
                      type="password"
                      className="form-control block w-full px-3 py-1.5 text-sm font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded-[16px] transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      id="exampleFormControlInput1"
                      placeholder="Email"
                    />
                  </div>
                  <p className="mb-2 text-xs font-poppins">Password</p>
                  <div className="mb-4 font-poppins">
                  <div class="flex items-center flex-row justify-end mr-3">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 absolute my-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                  </div>
                    <input
                      type="password"
                      className="form-control block w-full px-3 py-1.5 text-sm font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded-[16px] transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      id="exampleFormControlInput1"
                      placeholder="Password"
                    />
                    
                  </div>
                  <div className="text-center pt-2 mb-6 pb-1">
                    <button
                      className="inline-block font-poppins bg-[#7126B5] px-6 py-2.5 text-white font-medium text-sm leading-tight rounded-[16px] shadow-md focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out w-full mb-3"
                      type="button"
                      data-mdb-ripple="true"
                      data-mdb-ripple-color="dark"
                    >
                      Daftar
                    </button>
                  </div>
                  <div className="text-center text-sm font-poppins">
                    <p className="mb-0 mr-0">Sudah punya akun?
                      <a
                        href="#!"
                        className="text-[#7126B5] font-semibold pl-1 transition duration-200 ease-in-out"
                        >Masuk disini
                      </a>
                    </p>
                  </div>
                </form>
              </div>
            </div>           
          </div>
      </section>
        {/* <section className="h-screen ">
          <div className=" text-gray-800">
            <div
              className="flex xl:justify-center lg:justify-between justify-center items-center flex-wrap h-full"
            >
              <div className="grow-0 shrink-0 md:shrink-0 basis-auto xl:w-6/12 lg:w-6/12 md:w-12/12 md:mb-0 mt-0 ml-0">
              <Image
                    src={imageForm}
                    alt="Picture of the author"
                    className="w-full m-0"
                  />
              </div>
              <div className="xl:ml-20 xl:w-5/12 lg:w-5/12 md:w-8/12 mb-0 md:mb-0">
                <form>
                <div className="text-left text-2xl font-sans">
                    <p className="text-md font-bold mb-4">
                      Daftar
                    </p>
                  </div>

                  <div className="mb-6">
                    <input
                      type="text"
                      className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      id="exampleFormControlInput2"
                      placeholder="Email address"
                    />
                  </div>

                  <div className="mb-6">
                    <input
                      type="password"
                      className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      id="exampleFormControlInput2"
                      placeholder="Password"
                    />
                  </div>

                  <div className="flex justify-between items-center mb-6">
                    <div className="form-group form-check">
                      <input
                        type="checkbox"
                        className="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                        id="exampleCheck2"
                      />
                      <label className="form-check-label inline-block text-gray-800" id="exampleCheck2"
                        >Remember me</label
                      >
                    </div>
                    <a href="#!" className="text-gray-800">Forgot password?</a>
                  </div>

                  <div className="text-center lg:text-left">
                    <button
                      type="button"
                      className="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                    >
                      Login
                    </button>
                    <p className="text-sm font-semibold mt-2 pt-1 mb-0">
                      Don't have an account?
                      <a
                        href="#!"
                        className="text-red-600 hover:text-red-700 focus:text-red-700 transition duration-200 ease-in-out"
                        >Register</a
                      >
                    </p>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section> */}
      </main>

      
    </div>
  )
}
